### ISSUE TITLE
roughing it ribbon type error when paying with credit card

### ISSUE THREAD

**Issue by binary1230** [magfest/magstock#13]
this might just be a config option we didn't put in:

to repro: register a new attendee and select primitive campsite.  pay with credit card.  after successful payment, this comes up:
```
  File "/usr/local/uber/plugins/magstock/magstock/__init__.py", line 68, in roughing_it
    self.ribbon = c.ROUGHING_IT
  File "/usr/local/uber/plugins/uber/uber/config.py", line 284, in __getattr__
    raise AttributeError('no such attribute {}'.format(name))
AttributeError: no such attribute ROUGHING_IT
```

my guess is in the .yaml file we need to include the ROUGHING_IT ribbon type

**Comment by kitsuta** [comment]
Yup, that's the error. Easy fix.

**Comment by kitsuta** [comment]
Wait, in production config, it's already assigning that ribbon.

https://github.com/magfest/production-config/blob/master/event-magstock.yaml#L135

And a quick test on staging shows that this was fixed long ago.

**Comment by binary1230** [comment]
this is still happening for me

repro:  
1) preregister with site-type = Primitive (roughing it ribbon)
2) pay with credit card

---
I do agree the config looks right though so not sure yet what's up here

**Comment by kitsuta** [comment]
Whoops, my bad. I didn't test paying with a card. :x

**Comment by kitsuta** [comment]
On an unrelated note, this is another case where we could solve this better if we fixed the bug I encountered a while back with letting plugins add to enums without overridding them. Eli and I discussed it at the time and concluded that it was too much trouble, but this is another instance where a plugin should include a config option to prevent it breaking. Just sayin'.

**Comment by EliAndrewC** [comment]
> On an unrelated note, this is another case where we could solve this better if we fixed the bug I encountered a while back with letting plugins add to enums without overridding them. Eli and I discussed it at the time and concluded that it was too much trouble, but this is another instance where a plugin should include a config option to prevent it breaking. Just sayin'.

Agreed!  It's on my list of post-MAGFest refactorings that I linked awhile back in Google Docs.  It will definitely happen this year (as soon as things calm down enough that I have the time/energy to do actual coding again)!
